package jp.ac.asojuku.feprj.entity;



import java.io.Serializable;
import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.Table;

import lombok.Data;

/**
 * ルールテーブル モデルクラス.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
@Data
@Entity 
@Table(name="ANSWER")
public class AnswerEntity implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** rule_id. */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	/** name. */
	private String name;

	/** score. */
	private Integer score;

	/** time. */
	private Date time;

	/** question. */
	private Integer question;

	/**
	 * コンストラクタ.
	 */
	public AnswerEntity() {
	}
	

	@PrePersist
    public void onPrePersist() {
		setTime(new Date());
    }
}
